apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - args:
    - ruby
    - main.rb
    image: dprovest/bunny_on_k8s:latest
    name: app
    resources: {}
  restartPolicy: OnFailure
status: {}
