version: '3'

services:
  app:
    build: .
    image: dprovest/bunny_on_k8s:latest
    command: ruby main.rb
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - common-network
    deploy:
      replicas: 1

  rabbitmq:
      image: rabbitmq:management-alpine
      hostname: rabbit
      ports:
        - "5671:5671"
        - "5672:5672"
        - "15672:15672"
      labels:
        NAME: "rabbitmq"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      networks:
        - common-network
      deploy:
        replicas: 1

networks:
  common-network:
