apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    NAME: rabbitmq
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        image: rabbitmq:management-alpine
        name: rabbitmq
        ports:
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15672
        resources: {}
        volumeMounts:
        - mountPath: /etc/rabbitmq/rabbitmq.config
          name: rabbitmq-claim0
      hostname: rabbit
      restartPolicy: Always
      volumes:
      - name: rabbitmq-claim0
        persistentVolumeClaim:
          claimName: rabbitmq-claim0
status: {}
